apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o k8s-manifests-docker/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
    - name: "30030"
      port: 30030
      targetPort: 80
  selector:
    io.kompose.service: web
