apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-web-app.fullname" . }} 
  labels:
    {{- include "my-web-app.labels" . | nindent 4 }} 
spec:
  type: {{ .Values.service.type }} 
  ports:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.port }} 
      targetPort: {{ .Values.service.targetPort }} 
      protocol: TCP
      
  selector:
    {{- include "my-web-app.selectorLabels" . | nindent 4 }} 