apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o k8s-manifests-j/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o k8s-manifests-j/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: web
    spec:
      containers:
        - args:
            - /bin/sh
            - -c
            - sed -i 's/listen 80;/listen 3000;/' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'
          image: nginx:latest
          name: nginx-container
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/nginx/html/index.html
              name: web-cm0
              subPath: index.html
            - mountPath: /usr/share/nginx/html/styles.css
              name: web-cm1
              subPath: styles.css
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: index.html
                path: index.html
            name: web-cm0
          name: web-cm0
        - configMap:
            items:
              - key: styles.css
                path: styles.css
            name: web-cm1
          name: web-cm1
