name: Convert Docker Compose to Kubernetes

on:
  push:
    branches:
      - main  # Se ejecuta en cada push a main
  workflow_dispatch:  # Permite ejecución manual

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}  # Usar el token con permisos de escritura

      - name: Install Kompose
        run: |
          curl -L https://github.com/kubernetes/kompose/releases/latest/download/kompose-linux-amd64 -o kompose
          chmod +x kompose
          sudo mv kompose /usr/local/bin/

      - name: Convert docker-compose to Kubernetes
        run: |
          mkdir -p k8s-manifests
          kompose convert -f docker-compose.yaml -o k8s-manifests/

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s-manifests/
          git commit -m "Auto-converted docker-compose to Kubernetes manifests" || echo "No changes to commit"
          git push origin main
